// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Ambient module declaration for @sieve/wasm.
//
// @sieve/wasm is generated by wasm-pack and only available after
// publishing — the npm typecheck step in CI runs before the wasm
// bundle is built / published, so the package isn't yet present in
// node_modules. This stub gives tsc enough type info to compile
// @sieve/nextjs's wrapper code without resolving the real package.
//
// At runtime, when a user installs @sieve/wasm alongside @sieve/nextjs,
// the real wasm-pack-generated types override this stub.

declare module "@sieve/wasm" {
  export default function init(input?: unknown): Promise<unknown>;

  export interface Verdict {
    decision: "Allow" | "Flag" | "Block";
    score: number;
    findings: Array<{
      detector: string;
      severity: "Info" | "Warn" | "Block";
      message: string;
      matched_span: [number, number] | null;
      score: number;
      category: string;
    }>;
    normalized_input: string | null;
    canary_state: { canaries: string[] };
    canaries_leaked: Array<{
      canary: string;
      matched_span: [number, number];
      exact: boolean;
    }>;
    commitments_violated: Array<{
      kind: string;
      expected: string;
      observed: string;
      confidence: number;
    }>;
    latency_us: number;
  }

  export interface InstrumentedPrompt {
    system_prompt: string;
    canary_state: { canaries: string[] };
  }

  export type ScannerMode = "strict" | "balanced" | "monitor";

  export class Scanner {
    constructor(mode?: ScannerMode);
    scanInput(systemPrompt: string, userInput: string): Verdict;
    instrumentSystemPrompt(systemPrompt: string): InstrumentedPrompt;
    scanOutput(
      systemPrompt: string,
      output: string,
      canaryState: { canaries: string[] } | string,
    ): Verdict;
  }

  export const SIEVE_WASM_VERSION: () => string;
}
