# SPDX-License-Identifier: MIT OR Apache-2.0
"""Type stubs for sieve._native (pyo3-backed core)."""

from __future__ import annotations
from typing import Any, Literal

__version__: str

Decision = Literal["Allow", "Flag", "Block"]
Severity = Literal["Info", "Warn", "Block"]
Category = Literal[
    "UnicodeSmuggling",
    "KnownPattern",
    "EncodingPayload",
    "InstructionDensity",
    "LanguageSwitch",
    "HighEntropy",
    "CanaryLeak",
    "CommitmentViolation",
    "ToolCallAnomaly",
    "ConversationDrift",
    "Unknown",
]


class Finding:
    @property
    def detector(self) -> str: ...
    @property
    def severity(self) -> Severity: ...
    @property
    def message(self) -> str: ...
    @property
    def matched_span(self) -> tuple[int, int] | None: ...
    @property
    def score(self) -> float: ...
    @property
    def category(self) -> Category: ...


class CanaryState:
    def __init__(self, canaries: list[str] = ...) -> None: ...
    @property
    def canaries(self) -> list[str]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(s: str) -> "CanaryState": ...


class CanaryLeak:
    @property
    def canary(self) -> str: ...
    @property
    def matched_span(self) -> tuple[int, int]: ...
    @property
    def exact(self) -> bool: ...


class CommitmentViolation:
    @property
    def kind(self) -> str: ...
    @property
    def expected(self) -> str: ...
    @property
    def observed(self) -> str: ...
    @property
    def confidence(self) -> float: ...


class Verdict:
    @property
    def decision(self) -> Decision: ...
    @property
    def score(self) -> float: ...
    @property
    def findings(self) -> list[Finding]: ...
    @property
    def normalized_input(self) -> str | None: ...
    @property
    def canary_state(self) -> CanaryState: ...
    @property
    def canaries_leaked(self) -> list[CanaryLeak]: ...
    @property
    def commitments_violated(self) -> list[CommitmentViolation]: ...
    @property
    def latency_us(self) -> int: ...
    def is_allow(self) -> bool: ...
    def is_flag(self) -> bool: ...
    def is_block(self) -> bool: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...


class Scanner:
    def __init__(self) -> None: ...
    def scan_input(self, system_prompt: str, user_input: str) -> Verdict: ...
    def scan_output(
        self, system_prompt: str, output: str, canary_state: CanaryState
    ) -> Verdict: ...
